SM-000 | fix: non nullable bug
SwarmMarkets/trade-subgraph pull request #66
Opened 2022-02-21 13:53 UTC by ilamini

2022-02-21 13:57 UTC, ElvisKrop requested changes

2022-02-21 13:57 UTC, ElvisKrop commented on schema.rinkeby.graphql
> +  nftAddress: ERC1155Token!
```suggestion
  nft: ERC1155Token!
```

2022-02-21 13:57 UTC, ElvisKrop commented on src/mappings/dOTCManager.ts
> +  offer.nftAddress = event.params.nftAddress.toHexString()
```suggestion
  offer.nft = event.params.nftAddress.toHexString()
```

2022-02-21 14:00 UTC, ilamini commented on schema.rinkeby.graphql
> +  nftAddress: ERC1155Token!
Okay, this is a better name, please inform Maksim

2022-02-21 14:26 UTC, ElvisKrop approved these changes

2022-02-22 11:09 UTC, ElvisKrop approved these changes

2022-02-22 11:10 UTC, merged